#version: "3.8"

services:
  django-app:
    build: .
    container_name: django-app
    entrypoint: ["/app/entrypoint.sh"]
    command: gunicorn School.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/app/static_files  # Only needed for serving static files
      - media_data:/app/media          # Store uploaded media files
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      REDIS_HOST: redis
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: "*"
    depends_on:
      - db
      - redis
    networks:
      - mynetwork
    restart: always  # Ensure the service restarts on failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - django-app
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static_files
      - media_data:/app/media
    ports:
      - "80:80"
      - "443:443"  # Allow HTTPS traffic
    networks:
      - mynetwork

  celery-worker:
    build: .
    container_name: celery-worker
    command: ["celery", "-A", "School", "worker", "--loglevel=info"]
    depends_on:
      - django-app
      - redis
    restart: always
    networks:
      - mynetwork

  celery-beat:
    build: .
    container_name: celery-beat
    command: ["celery", "-A", "School", "beat", "--loglevel=info"]
    depends_on:
      - django-app
      - redis
      - celery-worker
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
  static_data:
  media_data:
