#version: '3.7'

services:
  django-app:
    build: .
    container_name: django-app
    entrypoint: ["/app/entrypoint.sh"]
    command: gunicorn School.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_data:/app/static_files
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      REDIS_HOST: redis # Add this line to connect to Redis
    depends_on:
      - db
      - redis # Add Redis as a dependency
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - django-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx config
      - static_data:/app/static_files                     # Serve static files
    ports:
      - "80:80"                                           # Expose port 80
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
  static_data:
