
services:
  django-app:
    build: .
    container_name: django-app
    entrypoint: ["/app/entrypoint.sh"]
    command: gunicorn School.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_data:/app/static_files  # Mount static files
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      REDIS_HOST: redis                 # Redis host added
    depends_on:
      - db                              # Ensure database is started first
      - redis                           # Redis as dependency
    networks:
      - mynetwork

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data       # Persistent PostgreSQL data storage
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"                     # Expose Redis port
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - django-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount custom Nginx config
      - static_data:/app/static_files                     # Serve static files
    ports:
      - "80:80"                                           # Expose Nginx on port 80
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
  static_data:
