[build]
  base = "School"  # The directory where your Django project resides
  publish = "School"  # Directory for static files
  command = "docker pull davedevspace/my-django-app:latest  && docker run -d -p 8000:8000 davedevspace/my-django-app:latest"
