# Generated by Django 5.1.3 on 2024-12-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='section',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='students.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.class'),
        ),
        migrations.AddField(
            model_name='studentparent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.parent'),
        ),
        migrations.AddField(
            model_name='studentparent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(related_name='students', through='students.StudentParent', to='students.parent'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.book'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.transaction'),
        ),
    ]
