# Generated by Django 5.1.3 on 2024-12-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
