# Generated by Django 5.1.5 on 2025-01-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='documents',
            field=models.FileField(blank=True, help_text='Upload student-related documents', null=True, upload_to='student_documents/'),
        ),
    ]
