# Generated by Django 5.1.5 on 2025-01-19 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('management', '0001_initial'),
        ('students', '0002_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.event'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='management.event'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='participant_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='lessonexchangerequest',
            name='teacher_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_1', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='lessonexchangerequest',
            name='teacher_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_2', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='management.examtype'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='students.student'),
        ),
        migrations.AddField(
            model_name='result',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='students.gradesection'),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='students.grade'),
        ),
        migrations.AddField(
            model_name='subject',
            name='single_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_subjects', to='students.grade'),
        ),
        migrations.AddField(
            model_name='result',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='management.subject'),
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.examtype'),
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='report_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='management.reportcard'),
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='management.subject'),
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.term'),
        ),
        migrations.AddField(
            model_name='schoolperformance',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_performance', to='management.term'),
        ),
        migrations.AddField(
            model_name='result',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='management.term'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='management.term'),
        ),
        migrations.AddField(
            model_name='examtype',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='management.term'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='grade_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='students.gradesection'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='lessonexchangerequest',
            name='lesson_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_1', to='management.timetable'),
        ),
        migrations.AddField(
            model_name='lessonexchangerequest',
            name='lesson_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_2', to='management.timetable'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'event', 'student', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectmark',
            unique_together={('student', 'subject', 'term', 'exam_type')},
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'subject', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='examtype',
            unique_together={('name', 'term')},
        ),
    ]
