# Generated by Django 5.1.3 on 2024-12-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
