# Generated by Django 5.1.5 on 2025-01-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email_address', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='logo/%Y/%m/%d')),
            ],
        ),
    ]
