# Generated by Django 5.1.3 on 2024-12-05 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_grade_subject_grade_assigned_result'),
        ('teachers', '0006_alter_teacher_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_subjects', to='teachers.teacher'),
        ),
    ]
