# Generated by Django 5.1.3 on 2024-12-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_performance_subject_alter_result_subject_and_more'),
        ('students', '0009_grade_section_delete_section'),
        ('teachers', '0008_remove_teacher_assigned_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rank', models.IntegerField()),
                ('date_of_report_card_generation', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentreportcard', to='students.student')),
            ],
            options={
                'unique_together': {('student_rank', 'date_of_report_card_generation')},
            },
        ),
        migrations.CreateModel(
            name='SubjectMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentperformances', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectperformances', to='teachers.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
