# Generated by Django 5.1.3 on 2024-12-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_reportcard_subjectmarks'),
        ('students', '0009_grade_section_delete_section'),
        ('teachers', '0008_remove_teacher_assigned_section'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectMarks',
            new_name='SubjectMark',
        ),
    ]
