# Generated by Django 5.1.4 on 2025-01-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_subjectmark_max_score_subjectmark_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmark',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
