# Generated by Django 5.1.3 on 2024-12-06 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_rename_subjectmarks_subjectmark'),
        ('students', '0009_grade_section_delete_section'),
        ('teachers', '0008_remove_teacher_assigned_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcard',
            old_name='date_of_report_card_generation',
            new_name='date_generated',
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'teacher_subject', 'term')},
        ),
        migrations.AddField(
            model_name='reportcard',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='management.term'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='total_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='teacher_subject',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='management.teachersubject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='term',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='management.term'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='students.student'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='student_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='teachersubject',
            unique_together={('teacher', 'subject', 'grade_assigned')},
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
        migrations.RemoveField(
            model_name='result',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='result',
            name='subject',
        ),
    ]
