# Generated by Django 5.1.4 on 2025-01-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_subjectmark_marks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examtype',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='examtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='examtype',
            name='term',
        ),
    ]
