# Generated by Django 5.1.3 on 2024-12-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_rename_date_of_report_card_generation_reportcard_date_generated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcard',
            old_name='date_generated',
            new_name='date',
        ),
    ]
