# Generated by Django 5.1.4 on 2025-01-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_examtype_unique_together_alter_examtype_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-start_date'], 'verbose_name': 'Term', 'verbose_name_plural': 'Terms'},
        ),
    ]
