# Generated by Django 5.1.5 on 2025-01-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='staff_number',
            field=models.CharField(default='TCH/000/00', max_length=20, unique=True),
        ),
    ]
