"""
Django settings for School project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import socket
from datetime import timedelta
from pathlib import Path

import dj_database_url
import redis
from decouple import config
from django.contrib import messages
from django.core.cache.backends.redis import RedisCache
from dotenv import load_dotenv
import environ
from redis.connection import BlockingConnectionPool

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-0yg9%d29(l9u^17*mm5=*%&jpev!x(&s(9q!ih12@i0a03zual'

# # SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # change to false in production
#
ALLOWED_HOSTS = ['school-kbah.onrender.com', 'www.stitchngalore.com',
                 'localhost']  # Replace '*' with your domain or IP for production

# Application definition

INSTALLED_APPS = [

    'apps.Manage.apps.ManageConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'phonenumber_field',
    'apps.students',
    'apps.teachers',
    'apps.management',
    'apps.accounts',
    'apps.website',
    'django_crontab',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_daraja',
    'channels',

    'django_celery_beat',
    'apps.schedules',
    'rest_framework',
    'rest_framework.authtoken',
    'django_ckeditor_5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # logs
    # 'apps.Manage.middleware.GroupRedirectMiddleware',
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Default authentication backend
    'apps.Manage.backend.StaffNumberAuthBackend',  # Your custom backend
)

# # settings.py
# AUTH_USER_MODEL = 'Manage.CustomUser'


ROOT_URLCONF = 'School.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ASGI application path
ASGI_APPLICATION = 'School.asgi.application'

REDIS_URL = os.getenv('REDIS_URL', 'redis://redis:6379/1')

# Caching settings
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Test Redis connection
try:
    r = redis.StrictRedis.from_url(REDIS_URL, decode_responses=True)
    r.ping()
    print("Connected to Redis successfully.")
except redis.exceptions.ConnectionError as e:
    print(f"Redis connection error: {e}")

#
# # Initialize environment variables
env = environ.Env()
environ.Env.read_env()  # Read from .env (for local dev)

DATABASE_URL = env.str("DATABASE_URL", default="")  # Read DATABASE_URL

if DATABASE_URL:
    DATABASES = {"default": dj_database_url.config(default=DATABASE_URL)}
else:
    print("Warning: No DATABASE_URL set!")
    DATABASES = {}

# # #celery test
# DATABASES = {
#     'default': dj_database_url.parse(os.getenv("DATABASE_URL", "postgresql://davedevspace:f2CN8IZAIL7zFg7LjhTgHyxZTtlJe4hL@dpg-cu6pc4i3esus73fcve20-a.oregon-postgres.render.com/school_db_1j40"))
# }




# # # Database Configuration
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": config("DB_NAME"),
#         "USER": config("DB_USER"),
#         "PASSWORD": config("DB_PASSWORD"),
#         "HOST": config("DB_HOST", default="localhost"),
#         "PORT": config("DB_PORT", default="5432"),
#     }
# }

# If using Celery
CELERY_BROKER_URL = 'redis://redis:6379/1'
CELERY_RESULT_BACKEND = 'redis://redis:6379/1'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# Redis setup for Django Channels (if using WebSockets)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('redis', 6379)],  # Redis container name from docker-compose.yml
        },
    },
}
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False  # Must be False for frontend to access CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'

# Ensure session cookies are secure and HTTP-only
SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Use database to store sessions
SESSION_COOKIE_AGE = 86400  # Session expires after 24 hours
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session on each request
SESSION_COOKIE_SAMESITE = None  # Allow cross-page session usage
SESSION_COOKIE_SECURE = False  # Set to True if using HTTPS
SESSION_COOKIE_HTTPONLY = False  # Allow JavaScript to access sessionid
SESSION_COOKIE_NAME = "sessionid"

CKEDITOR_5_CONFIGS = {
    'default': {
        "upload_url": "/ckeditor5/upload/",
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'underline', '|',
            'link', 'bulletedList', 'numberedList', 'blockQuote',
            'imageUpload', 'insertTable', '|', 'undo', 'redo'
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', 'imageStyle:full', 'imageStyle:side'
            ]
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells'
            ]
        },
        'mediaEmbed': {'previewsInData': True},
    }
}

# pip install django-storages
# django-storages documentation
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

AWS_ACCESS_KEY_ID = 'your-access-key-id'
AWS_SECRET_ACCESS_KEY = 'your-secret-access-key'
AWS_STORAGE_BUCKET_NAME = 'your-bucket-name'

pool = BlockingConnectionPool.from_url(
    REDIS_URL, max_connections=50, timeout=10
)
r = redis.StrictRedis(connection_pool=pool, decode_responses=True)

WSGI_APPLICATION = 'School.wsgi.application'
# SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Email settings for mail.valuetech.co.ke
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.valuetech.co.ke'  # Outgoing mail server
EMAIL_PORT = 465  # SMTP port for secure connections
EMAIL_USE_SSL = True  # Use SSL for secure email transmission
EMAIL_HOST_USER = 'admin@valuetech.co.ke'  # Your email address
EMAIL_HOST_PASSWORD = 'davedevspace'  # Replace with your email account's password
DEFAULT_FROM_EMAIL = 'ValueTech Admin <admin@valuetech.co.ke>'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'error.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# General Settings
DEBUG = config("DEBUG", default=True, cast=bool)
SECRET_KEY = config("DJANGO_SECRET_KEY", default="fallback_secret_key")

# Static/Media File Handling
# USE_S3 = config("USE_S3", default=False, cast=bool)
# if USE_S3:
#     AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
#     AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
#     AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
#     STATIC_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/static/"
#     MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/media/"
# else:
#     STATIC_URL = "/static/"
#     MEDIA_URL = "/media/"
#     STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
#     MEDIA_ROOT = os.path.join(BASE_DIR, "media")
#     STATIC_ROOT = os.path.join(BASE_DIR, "static_files")
#


STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static_files')  # for  deployment

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# This ensures that media files are served correctly in development


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',  # Only JSON responses
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        "rest_framework.authentication.SessionAuthentication",  # Enables session-based auth
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # Default: Require authentication for all views
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Short-lived access token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Longer-lived refresh token
    'ROTATE_REFRESH_TOKENS': True,  # Issue a new refresh token when used
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist old refresh tokens
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"  # Or the framework you use
CRISPY_TEMPLATE_PACK = "bootstrap5"

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

LOGIN_URL = 'login'

# The Mpesa environment to use
# Possible values: sandbox, production

MPESA_ENVIRONMENT = 'sandbox'

# Credentials for the daraja app

MPESA_CONSUMER_KEY = os.getenv('mpesa_consumer_key')
MPESA_CONSUMER_SECRET = os.getenv('mpesa_consumer_secret')

# Shortcode to use for transactions. For sandbox  use the Shortcode 1 provided on test credentials page

MPESA_SHORTCODE = 'mpesa_shortcode'

# Shortcode to use for Lipa na MPESA Online (MPESA Express) transactions
# This is only used on sandbox, do not set this variable in production
# For sandbox use the Lipa na MPESA Online Shorcode provided on test credentials page

MPESA_EXPRESS_SHORTCODE = 'mpesa_express_shortcode'

# Type of shortcode
# Possible values:
# - paybill (For Paybill)
# - till_number (For Buy Goods Till Number)

MPESA_SHORTCODE_TYPE = 'paybill'

# Lipa na MPESA Online passkey
# Sandbox passkey is available on test credentials page
# Production passkey is sent via email once you go live

MPESA_PASSKEY = 'mpesa_passkey'

# Username for initiator (to be used in B2C, B2B, AccountBalance and TransactionStatusQuery Transactions)

MPESA_INITIATOR_USERNAME = 'initiator_username'

# Plaintext password for initiator (to be used in B2C, B2B, AccountBalance and TransactionStatusQuery Transactions)

MPESA_INITIATOR_SECURITY_CREDENTIAL = 'initiator_security_credential'
